version: '3.8'

services:
  secapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - URLSCAN_API_KEY=${URLSCAN_API_KEY}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=False
      - PORT=5000
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
